urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout

from mapcal import views

# ADD to mysite/urls.py:
# url(r'^mapcal/', include('mapcal.urls')),
#  ('mapcal.urls' is inside quotes)

urlpatterns = patterns('',
    url(r'^$', views.listappts),
    url(r'^all/$', views.listallappts),
    url(r'^alltags/$', views.alltags),
    url(r'^(?P<tag_id>\d+)/tag/$', views.bytag),
    url(r'^(?P<appt_id>\d+)/detail/$', views.detail, name="appt_detail"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/add/$', views.add),
    url(r'^delete/$', views.delete_appt),
    url(r'^accounts/login/$', login),
    url(r'^accounts/dologin/$', views.mapcal_login),
    url(r'^accounts/logout/$', views.logout_view),
    url(r'^(?P<appt_id>\d+)/edit/$', views.edit),
    #url(r'^month/$', views.monthview),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/month/$', views.monthview),
)

models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=60)
    def __str__(self):
        return self.name
    def __unicode__(self):
        return self.name

class Appt(models.Model):
    user = models.ForeignKey(User)
    time = models.DateTimeField('time and date')
    desc = models.CharField(max_length=100)
    notes = models.CharField(max_length=300, blank=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    def __str__(self):
        return self.desc
    def __unicode__(self):
        return self.desc

class Marker(models.Model):
    appt = models.ForeignKey(Appt)
    lat = models.FloatField()
    lng = models.FloatField()
    desc = models.CharField(max_length=60, blank=True)
    def __str__(self):
        return "%s: %f, %f" % (self.desc, self.lat, self.lng)
    def __unicode__(self):
        return "%s: %f, %f" % (self.desc, self.lat, self.lng)

templates/mapcal/addform.html
{% load staticfiles %}

<html>
<head>
<title>Map Calendar - add appointment</title>
<style type="text/css">
html, body { height: 100%; width: 100% }
#mymap { width: 400px; height: 50%; }
</style>
  <link rel="stylesheet" href="{% static 'mapcal/css/ui-lightness/jquery-ui-1.10.3.custom.css' %}">
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script src="{% static 'mapcal/js/jquery-1.9.1.js' %}"></script>
<script src="{% static 'mapcal/js/jquery-ui-1.10.3.custom.min.js' %}"></script>
<script type="text/javascript">
  var map;

var markarr = [];

function addMarker(lat, lng) {
  tmpmarker = new google.maps.Marker({ position: newLatLng(lat, lng) });
  tmpmarker.setMap(map);
  markarr.push(tmpmarker);
}

function formatLatLng(latLng) {
  return latLng.lat() + "," + latLng.lng();
}

function incNumMarkers() {
  $("#nummarkers").val(parseInt($("#nummarkers").val()) + 1);
}

function addToMarkerCoords(txt) {
  $("#markercoords").val($("#markercoords").val() + txt + ";");
}
  

    var geocoder = new google.maps.Geocoder();

    function addressToLatLng(addressStr) {
      geocoder.geocode({'address': addressStr}, function(results, status) {
        if(status == google.maps.GeocoderStatus.OK) {
          incNumMarkers();
          addToMarkerCoords(formatLatLng(results[0].geometry.location));
          console.log(formatLatLng(results[0].geometry.location));
          map.setCenter(results[0].geometry.location);
          addMarker(results[0].geometry.location.lat(), results[0].geometry.location.lng());
        } else {
          console.log("Error: Geocoder status " + status);
        }
      });
    }

  function initialize() {
  var mapOptions = { center: new google.maps.LatLng(-23.55, -46.64), zoom: 14,
  mapTypeId: google.maps.MapTypeId.ROADMAP };
  map = new google.maps.Map(document.getElementById("mymap"), mapOptions);

  {% for marker in appt.marker_set.all %}
    addMarker({{ marker.lat }}, {{ marker.lng }});
    incNumMarkers();
    addToMarkerCoords("{{ marker.lat }},{{ marker.lng}}");
    map.setCenter(newLatLng({{ marker.lat }}, {{ marker.lng }}));
  {% endfor %}
  

    google.maps.event.addListener(map, 'click', function(event) {
        clickLat = event.latLng.lat();
        clickLng = event.latLng.lng();
        addMarker(clickLat, clickLng);
        $("#nummarkers").val(parseInt($("#nummarkers").val()) + 1);
        $("#markercoords").val($("#markercoords").val() + clickLat + "," + clickLng + ";");
    });
  }

  var newLatLng = function(lat, lng) {
  return new google.maps.LatLng(lat, lng);
  }

  google.maps.event.addDomListener(window, 'load', initialize);

</script>

</head>
<body>
  {% include "mapcal/nav.html" %}

  <table border="0" width="100%" height="100%">
    <tr>
      <td valign="top">
  
<form action="/mapcal/{% now "Y" %}/{% now "m" %}/{% now "d" %}/add/" method="post">
  <input type="hidden" name="del_id" value="{{ appt.id }}">
  <input type="hidden" name="nummarkers" id="nummarkers" value="0">
  <input type="hidden" name="markercoords" id="markercoords">

  <p>Date:<br>
    <input type="text" name="ymd" id="datepicker">
<br>
24-h time (hh:mm):<br>
<input type="text" name="time" value="{{ appt.time|date:"H:i" }}"></p>

  <p>description:<br>
    <input type="text" name="desc" value="{{ appt.desc }}"></p>
  <p>notes:<br>
    <textarea name="notes" rows="3" cols="28">{{ appt.notes }}</textarea></p>
  <p>tags:<br>
  <input type="text" name="tag1" value="{{ tag1 }}"><br>
  <input type="text" name="tag2" value="{{ tag2 }}"><br>
  <input type="text" name="tag3" value="{{ tag3 }}">
  </p>


  Address:<br>
  <input type="text" name="address" id="addressInput">
  <button type="button" id="geocodeAddress" onclick="addressToLatLng($('#addressInput').val());">find address</button><br><br>
  
  <input type="submit" value="{% if appt %}Update{% else %}Add{% endif %} appt"><br><br>
{% csrf_token %}

</form>
      </td>
      <td width="70%" height="500px" valign="top">
        <div id="mymap" style="width: 100%; height: 100%"></div>
      </td>
    </tr>
  </table>
        {{ datetoadd }}

<script type="text/javascript">
  $("#datepicker").datepicker();
$("#datepicker").datepicker("option", "dateFormat", "yy-mm-dd");
$("#datepicker").datepicker("setDate", "{{ datetoadd }}")

{% if appt %}
  $("#datepicker").datepicker("setDate",
  new Date({{ appt.time|date:"Y" }}, {{ appt.time|date:"m" }} - 1,
           {{ appt.time|date:"d" }}, 9, 30, 0, 0, 0));
{% endif %}
</script>

</body>
  </html>

templates/mapcal/alltags.html
<html>
  <head>
    <title>Map Calendar - all tags</title>
  </head>
  <body>
    {% include "mapcal/nav.html" %}
    <b>All tags</b><br><br>
    {% for tag in tags %}
    <a href="/mapcal/{{ tag.id }}/tag/">{{ tag.name }}</a>{% if not forloop.last %} | {% endif %}
    {% endfor %}
  </body>
</html>

templates/mapcal/bytag.html
<html>
  <head>
    <title>List by tag</title>
  </head>
  
  <body>
    {% include "mapcal/nav.html" %}
    <b>{{ tag.name }}</b><br><br>
    {% for appt in appts %}
    <a href="/mapcal/{{ appt.id }}/detail/">{{ appt.time|date:"D, d M Y, P" }}: {{ appt.desc }}</a>
    <br>
    {% endfor %}
  </body>
</html>

templates/mapcal/cssblock.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'mapcal/css/ui-lightness/jquery-ui-1.10.3.custom.css' %}">

templates/mapcal/detail.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
<title>appointment detail</title>
<style type="text/css">
html, body { height: 100%; width: 100% }
#mymap { width: 100%; height: 100%; }
</style>
{% include "mapcal/cssblock.html" %}

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script src="{% static 'mapcal/js/jquery-1.9.1.js' %}"></script>
<script src="{% static 'mapcal/js/jquery-ui-1.10.3.custom.min.js' %}"></script>
<script type="text/javascript">
  var map;

var markarr = [];

function addMarker(lat, lng) {
  tmpmarker = new google.maps.Marker({ position: newLatLng(lat, lng) });
  tmpmarker.setMap(map);
  markarr.push(tmpmarker);
}


  function initialize() {
  var mapOptions = { center: new google.maps.LatLng(0.0, 0.0), zoom: 16,
  mapTypeId: google.maps.MapTypeId.ROADMAP };
  map = new google.maps.Map(document.getElementById("mymap"), mapOptions);


  {% for marker in appt.marker_set.all %}
    addMarker({{ marker.lat }}, {{ marker.lng }});
    map.setCenter(newLatLng({{ marker.lat }}, {{ marker.lng }}));
  {% endfor %}

  }

  var newLatLng = function(lat, lng) {
    return new google.maps.LatLng(lat, lng);
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>

</head>
<body>
{% include "mapcal/nav.html" %}

<table border="0" width="100%" height="100%">
  <tr>
    <td valign="top">

      <b>{{ appt }}</b>
      ({% for tag in appt.tags.all %}
      <a href="/mapcal/{{ tag.id }}/tag/">{{ tag.name }}</a>
      {% if not forloop.last %}|{% endif %}
      {% endfor %})

      | <a href="/mapcal/{{ appt.id }}/edit/">Edit</a> |
      <a href="http://freezoo.alwaysdata.net/free/googlemaps/geocodeprint.html" target="_blank">b&amp;w map</a>
      <br>
      
{{ appt.time|date:"D, d M Y, P" }}<br><br>
{{ appt.notes }}

<form action="/mapcal/delete/" method="post">
  <input type="hidden" name="apptid" value="{{ appt.id }}">
  <input type="submit" value="Delete appt.">
  {% csrf_token %}
</form>

      <div id="datepicker" width="100%"></div>
    </td>
    <td width="70%" height="500px" valign="top">
      <div id="mymap" style="width: 100%; height: 100%"></div>
    </td>
  </tr>
</table>


<script type="text/javascript">
$("#datepicker").datepicker();
$("#datepicker").datepicker("setDate", new Date({{ appt.time|date:'Y' }}, {{ appt.time|date:'m' }} - 1, {{ appt.time|date:'d' }}, 9, 30, 0, 0, 0));
</script>

</body>
</html>

templates/mapcal/listappts.html
<html>
  <head>
    <title>Mapcal - {{ user.username }}</title>
  </head>
  
  <body>
    {% include "mapcal/nav.html" %}

    <table border="0">
    {% for appt in appts %}
    <tr><td>
        <a href="/mapcal/{{ appt.id }}/detail">{{ appt.time|date:"D, d M Y, P" }}: {{ appt.desc }}</a>
      </td>
      <td>&nbsp;&nbsp;&nbsp;</td>
      <td>
      {% for tag in appt.tags.all %}
      <a href="/mapcal/{{ tag.id }}/tag/">{{ tag.name }}</a>{% if not forloop.last %},{% endif %} 
      {% endfor %}
      </td></tr>
      {% endfor %}
      </table>
  </body>
</html>

templates/mapcal/month.html
<html>
  <head>
    <title>Monthly view</title>
  </head>
  
  <body>
    {% include "mapcal/nav.html" %}


    <table border="1" width="98%">
    <tr>
    <td><a href="/mapcal/{{ prevlink }}/month">&lt;&lt; previous</a></td>
    <td colspan="5" align="center"><b>{{ longmonth }} {{ year }}</b></td>
    <td align="right"><a href="/mapcal/{{ nextlink }}/month">next &gt;&gt;</a></td>
    </tr>
<tr>
<td>Sunday</td>
<td>Monday</td>
<td>Tuesday</td>
<td>Wednesday</td>
<td>Thursday</td>
<td>Friday</td>
<td>Saturday</td>

</tr>
<tr>
{% for n in placeholder %}
<td width="14%" valign="top" {% ifequal yr thisyear %} {% ifequal mo thismonth %} {% ifequal n today %}bgcolor="#ffff77"{% endifequal %} {% endifequal %} {% endifequal %}>
<b>
  <a href="/mapcal/{{ yr }}/{{ mo}}/{{ n }}/add">{{ n }}</a></b>
  <br>
  {% for day in days %}
    {% ifequal day.d n %}
      <a href="/mapcal/{{ day.id }}/detail" title="{{ day.time|date:"P" }}">{{ day.detail }}</a> <br>
    {% endifequal %}
  {% endfor %}
  </td>
  {% if forloop.counter|divisibleby:7 %}
    </tr><tr>
  {% endif %}
{% endfor %}
</tr>
  </body>
</html>

templates/mapcal/nav.html
<table border="0" width="100%"><tr><td bgcolor="#99eeff">

      <a href="/mapcal/all/">View all appts.</a> |
      <a href="/mapcal/">View current appts.</a> |
      <a href="/mapcal/alltags">Browse tags</a> |
      <a href="/mapcal/{% now "Y" %}/{% now "n" %}/month/">Current month</a> |
      <a href="/mapcal/{% now "Y" %}/{% now "n" %}/{% now "d" %}/add/">Add new appt.</a>
      <br>
      <i>{% now "D, d M Y, P" %}</i>
    </td>

    <td align="right" bgcolor="#ffdd99" valign="top"><a href="/mapcal/accounts/logout/">Log out</a> ({{ user.username }})</td></tr></table>

templates/mapcal/staticmap.html
<!DOCTYPE html>
<html>
<head>
<title>google maps for chrome</title>
<style type="text/css">
html, body { margin: 0; padding: 0; height: 100%; width: 100% }
#mymap { width: 400px; height: 100%; }
</style>
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script src="jquery.js"></script>
<script type="text/javascript">
  var map;

var markarr = [];

function addMarker(lat, lng) {
  tmpmarker = new google.maps.Marker({ position: newLatLng(lat, lng) });
  tmpmarker.setMap(map);
  markarr.push(tmpmarker);
}


  function initialize() {
  var mapOptions = { center: new google.maps.LatLng(0.0, 0.0), zoom: 2,
  mapTypeId: google.maps.MapTypeId.ROADMAP };
  map = new google.maps.Map(document.getElementById("mymap"), mapOptions);


addMarker(45, -74);
addMarker(44, -73);
addMarker(43, -72);

map.setCenter(newLatLng(45,-74));
    
  }

  var newLatLng = function(lat, lng) {
  return new google.maps.LatLng(lat, lng);
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>

</head>
<body>
simple add/remove markers
<button id="btnRemove">remove markers</button>
<button id="btnAdd">add markers</button>
<div id="mymap" width="100%">
</div>
<script type="text/javascript">

$("#btnRemove").click(function () {
    for (var i = 0; i < markarr.length; i++) {
      markarr[i].setMap(null);
    }
    markarr = [];
  });

$("#btnAdd").click(function () {
  addMarker(46,-72);
});
</script>

</body>
</html>